apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: clickhouse 
spec:
  selector:
    app: clickhouse-server
  type: ClusterIP
  ports:
    - name: tcp
      port: 9000
      targetPort: 9000
    - name: http
      port: 8123
      targetPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service-np
  namespace: clickhouse 
spec:
  ports:
    - name: tcp
      nodePort: 30002
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: http
      nodePort: 30003
      port: 8123
      protocol: TCP
      targetPort: 8123
  selector:
    app: clickhouse-server 
  type: NodePort
